[package]
name = "addict"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.13", features = ["audio"] }
#rfd = { version = "0.15.2", default-features = false, features = ["gtk3"]}
